proxy:
  title: Open Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  hide-navbar: true
  specs:
  - id: cpp
    display-name: CPP
    container-cmd: ["R", "-e", "shiny::runApp('/root/CPP', host='0.0.0.0', port=3838)"]
    container-image: johnsonan/cpp
  docker:
    url: http://localhost:2375
    port-range-start: 20000
    port-range-end: 20009
logging:
  file:
    shinyproxy.log
